### ISSUE TITLE
Can't change "wrapperStyleName" for components that exist in a MasonryLayout

### ISSUE THREAD

**Issue by cradoi** [alump/Masonry#10]
My intention is to have components that can resize (minimize/maximize).

I have declared a MasonryLayout object.
In this I'm adding components by calling: masonryLayout.addComponent(componentX)
I would like to change the style for componentX in order to add for example "masonry-double-wide" (MasonryLayout.DOUBLE_WIDE_STYLENAME) on it.

I've tried to remove all the components from the masonryLayout by calling ".removeAllComponents" or by iterating through all the components from the layout by calling ".removeComponent". After this, I'm trying to re-add the same "componentX" into the layout by calling: masonryLayout.addComponent(componentX, MasonryLayout.DOUBLE_WIDE_STYLENAME).

Inspecting the div into html displays only: "masonry-item" and not "masonry-item masonry-double-wide" as would be the case if I'd have added from the beginning "componentX" with the double style on it.

Thank you

**Comment by alump** [comment]
I will check this out soon.

**Comment by alump** [comment]
Will be fixed to 0.5.0 by adding updateComponentWrapperStyleName(Component childComponent, String wrapperStyleName) method. So you do not have to remove and add back just to change wrapper styling.

**Comment by cradoi** [comment]
When do you estimate that build 0.5.0 will be available?

**Comment by alump** [comment]
Today, but HTML5 Drag'n drop reordering of items has to be removed from 0.5.0. Hopefully you didn't use that feature.

**Comment by alump** [comment]
Released
