### ISSUE TITLE
Sorting animation effect

### ISSUE THREAD

**Issue by Artgit** [alump/Masonry#12]
Right now I'm looking for an implementation/adapter of JavaScript component Isotope http://isotope.metafizzy.co/sorting.html for Vaadin 7 framework.

I especially looking for a some Vaadin component with a sorting animation effect.

Is any chance to get this functionality based on Masonry component ?

**Comment by alump** [comment]
I just implemented this feature to my GridStackLayout add-on. In **few hours** I will release it's 0.3.0 with nice animated sorting/reodering functionality provided to server side.

Just enable animations with .setAnimated(true) and then use .moveComponent(child, newX, newY) and you should get nice transitions.

Directory: https://vaadin.com/directory#!addon/gridstack-add-on
GitHub: https://github.com/alump/GridStack

Sorry closing this ticket, as I think this would not be possible with Masonry add-on.

**Comment by Artgit** [comment]
@alump Thank you very much for your answer. 

Looking forward to the upcoming release of GridStackLayout. Thanks again!

**Comment by Artgit** [comment]
@alump could you please take a look into my following question: https://github.com/alump/GridStack/issues/10 ?
