### ISSUE TITLE
"Live" preview during drag and drop

### ISSUE THREAD

**Issue by lorenzobenvenuti** [alump/Masonry#6]
Hi,

we noticed that reordering the tiles can be quite confusing for an user: sometimes the layout algorithm can give counterintuitive results. It would be really helpful to have a "live" preview of the tiles position while dragging. An example that uses the Packery JS library can be found here: http://packery.metafizzy.co; I don't know if it can be implemented easily with Masonry.

Thank you,

lorenzo

**Comment by alump** [comment]
I assume 0.4.0 works as wanted, so closing this.
