### ISSUE TITLE
Update problems after theme changed

### ISSUE THREAD

**Issue by TimeLord2004** [alump/Masonry#7]
Hi, we are using the DnDMasonryLayout in our main view of our app and it's working nicely until changing theme.
I.e our MainUI extends UI and is annotated with @Theme("abc"). When we call setTheme("xyz"), which is really just a minor scss extension of the first theme but with minor colour changes, most of the masonry layout disappears, only the top part (about 35px) is repainted. The area below this is completely empty, no divs or anything, so there is nothing to inspect.

Is there something that we need to call against the DnDMasonryLayout so that it renders correctly after the theme change?

BTW, if I change from the DnDMasonryLayout to a simple GridLayout for example, the change of theme works ok.

**Comment by TimeLord2004** [comment]
Another footnote: after calling setTheme we experimented by adding Thread.sleep(1000) then navigating back to the view we're on... it doesn't help, but if we navigate to the view a second time it re-renders and it's ok.
We're just trying to avoid the need to do a browser refresh and that's a bit of a hack (and might not help if that sleep isn't long enough)... but does it hint at what's wrong?

**Comment by alump** [comment]
I have to write test case to see what is happening here. This this correct...

- Have application with theme "A" using DnDMasonryLayout
- Make application to change it's theme to "B" (that is based on A)

Expected outcome:
DnDMasonryLayout keeps on working as before

Actual outcome:
DnDMasonryLayout component disappears from client rendering

**Comment by TimeLord2004** [comment]
Yes this is mostly correct except:
    "DnDMasonryLayout component disappears from client rendering"
    Should read something like:
    "Only the top approximately 35px of the DnDMasonryLayout component
    (and the widgets it contains) appears in the client rendering"
    
    Sami Viitanen wrote:
    
    
      I have to write test case to see what is happening here. This
        this correct...
      
        Have application with theme "A" using DnDMasonryLayout
        Make application to change it's theme to "B" (that is based
          on A)
      
      Expected outcome:
        DnDMasonryLayout keeps on working as before
      Actual outcome:
        DnDMasonryLayout component disappears from client rendering
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
      
      
      
      
No virus found in this incoming message.
Checked by AVG - www.avg.com 
Version: 9.0.935 / Virus Database: 4311.1.1/8898 - Release Date: 03/28/15 15:01:00

**Comment by alump** [comment]
I wrote test case to demo app, but there masonry component continued to work. So I need more information. Also please try to use 0.4.0, if you are using older versions.

**Comment by TimeLord2004** [comment]
Ok, can give 0.4.0 but to give it a fair shot will have to refactor code that uses the now deprecated DnDMasonryLayout (and DnDMasonryLayout.DnDMasonryReorderListener?)

0.4.0 was showing in GitHub as 'work started' but you've just committed MasonryDndReorderedEvent.java with the label '0.4.0 is here'. Does this mean we can treat 0.4.0 as finished?

**Comment by TimeLord2004** [comment]
Hi, it seems we fixed it by accident - we had a background gradient on our UI which we've now removed, and changing themes now works ok, even without any delays :-)
We were still on 0.3.0 and have just upgraded to 0.4.0 and that's good too :-)

FYI, in case you want to try it, this is what we removed from our main scss:
```
	.v-ui {
		background-image: -o-linear-gradient(180deg, #A76378 0%, #AB6D58 100%);
		background-image: -moz-linear-gradient(180deg, #A76378 0%, #AB6D58 100%);
		background-image: -ms-linear-gradient(180deg, #A76378 0%, #AB6D58 100%);
		background-image: linear-gradient(180deg, #A76378 0%, #AB6D58 100%);
	}
```
If I understand correctly, browsers implement a gradient like this as a pseudo-image(?) and maybe there is some sort of timing or reflow problem happening related to that.

Anyway, for now we're good! :-)
