### ISSUE TITLE
Where did the 0.4.0-SNAPSHOT go?

### ISSUE THREAD

**Issue by inahas** [alump/Masonry#8]
My build references the 0.4.0-SNAPSHOT which worked until at least 10 days ago but now the build breaks with an error:

[ERROR] Failed to execute goal on project xxxx: Could not resolve dependencies for project xxxx:vaadin:war:1.0.0-SNAPSHOT: Could not find artifact org.vaadin.alump.masonry:masonry-addon:jar:0.4.0-SNAPSHOT in vaadin-addons (http://maven.vaadin.com/vaadin-addons) -> [Help 1]

I am using the 0.4.0 version because it fixed a bug with inserting/removing components using an index and resolves the issue with the addons.css compilation. HELP!

**Comment by alump** [comment]
I will now release current code as 0.4.0, so move to use that.
